module CF
  module MCP
    module Models
      class FunctionDoc < DocItem
        class Parameter < ::Data
          attr_reader name: String
          attr_reader description: String

          def self.new: (String name, String description) -> instance
                      | (name: String, description: String) -> instance
        end

        attr_accessor signature: String?
        attr_accessor parameters: Array[Parameter]
        attr_accessor return_value: String?

        def initialize: (name: String, ?signature: String?, ?parameters: Array[Parameter]?, ?return_value: String?, **untyped kwargs) -> void

        def to_h: () -> Hash[Symbol, untyped]

        def to_summary: () -> String

        def to_text: (?detailed: bool, ?index: Index?) -> String

        def build_signature_lines: () -> Array[String]

        def build_type_specific_lines: () -> Array[String]
      end
    end
  end
end
