module CF
  module MCP
    module Tools
      class GetDetails < ::MCP::Tool
        extend ResponseHelpers

        TITLE: String
        NAMING_TIP: String

        def self.call: (name: String, ?server_context: server_context) -> ::MCP::Tool::Response
      end
    end
  end
end
