module CF
  module MCP
    module Tools
      class ParameterSearch < ::MCP::Tool
        extend ResponseHelpers

        TITLE: String

        def self.call: (type: String, ?direction: String, ?server_context: server_context) -> ::MCP::Tool::Response
      end
    end
  end
end
